src/Entity/Comment.php
<?php

namespace App\Entity;

use App\Repository\CommentRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommentRepository::class)]
class Comment
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $content = null;

    #[ORM\Column(length: 150)]
    private ?string $user_name = null;

    #[ORM\Column(nullable: true)]
    private ?bool $is_valid = false;

    #[ORM\ManyToOne(inversedBy: 'comments')]
    private ?User $validator = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): static
    {
        $this->content = $content;

        return $this;
    }

    public function getUserName(): ?string
    {
        return $this->user_name;
    }

    public function setUserName(string $user_name): static
    {
        $this->user_name = $user_name;

        return $this;
    }

    public function isIsValid(): ?bool
    {
        return $this->is_valid;
    }

    public function setIsValid(?bool $is_valid): static
    {
        $this->is_valid = $is_valid;

        return $this;
    }

    public function getValidator(): ?User
    {
        return $this->validator;
    }

    public function setValidator(?User $validator): static
    {
        $this->validator = $validator;

        return $this;
    }

    public function __toString(): string
    {
        return $this->id;
    }
}

src/Entity/Image.php
<?php

namespace App\Entity;

use Symfony\Component\HttpFoundation\File\File;
use DateTimeImmutable;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\ImageRepository;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

#[Vich\Uploadable]
#[ORM\Entity(repositoryClass: ImageRepository::class)]
class Image
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[Vich\UploadableField(mapping: 'gift', fileNameProperty: 'file_name', size: 'fileSize')]
    private ?File $file = null;

    private ?int $fileSize = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $file_name = null;

    #[ORM\ManyToOne(inversedBy: 'images')]
    private ?Gift $gift = null;

    #[ORM\Column(nullable: true)]
    private ?bool $isThumbnail = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updatedAt = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getGift(): ?Gift
    {
        return $this->gift;
    }

    public function setGift(?Gift $gift): static
    {
        $this->gift = $gift;

        return $this;
    }

    public function getFile(): ?File
    {
        return $this->file;
    }

    public function setFile(?File $file = null): static
    {
        $this->file = $file;

        if ($file) {
            $this->updatedAt = new DateTimeImmutable();
        }

        return $this;
    }

    public function getFileName(): ?string
    {
        return $this->file_name;
    }

    public function setFileName(?string $file_name): static
    {
        $this->file_name = $file_name;

        return $this;
    }

    public function getFileSize(): ?int
    {
        return $this->fileSize;
    }

    public function setFileSize(?int $fileSize): static
    {
        $this->fileSize = $fileSize;

        return $this;
    }

    public function getIsThumbnail(): ?bool
    {
        return $this->isThumbnail;
    }

    public function setIsThumbnail(?bool $isThumbnail): static
    {
        $this->isThumbnail = $isThumbnail;

        return $this;
    }

    public function setUpdatedAt(\DateTimeImmutable $updatedAt): static
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function __toString()
    {
        return $this->file_name;
    }
}

templates/_partials/_addflash.html.twig
<div class="position-absolute z-1 top-0 left-0 w-100">
  {% for label, messages in app.flashes %}
    {% for message in messages %}
      <div class="alert alert-{{ label }} m-1">
        <button type="button" class="btn m-0 close position-absolute top-50 end-0 translate-middle-y" data-bs-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        {{ message|raw }}
      </div>
    {% endfor %}
  {% endfor %}
</div>

templates/_partials/_comments.html.twig
<div id="carouselComment" class="carousel slide" style="height: 300px;">
  <div class="carousel-inner h-100 px-0 px-md-2 px-lg-4">
    {% for comment in comments %}
      <div class="h-100 w-100 px-0 px-md-5 carousel-item {% if loop.index == 1 %}active{% endif %}">
        <div class="d-flex h-100 align-items-center">
          <div class="bg-white bg-opacity-75 px-3 px-md-5 py-3 mx-5 rounded mx-2 h-auto">
            <p class="fst-italic">"{{ comment.content }}"</p>
            <p class="text-end text-capitalize fs-4 handwrite">{{ comment.userName }}</p>
          </div>
        </div>
      </div>
    {% endfor %}
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselComment" data-bs-slide="prev">
      <span class="w-auto" aria-hidden="true">
        <svg xmlns="http://www.w3.org/2000/svg" height="50" viewBox="0 -960 960 960" width="50">
          <path d="M560-240 320-480l240-240 56 56-184 184 184 184-56 56Z" />
        </svg>
      </span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselComment" data-bs-slide="next">
      <span class="w-auto" aria-hidden="true">
        <svg xmlns="http://www.w3.org/2000/svg" height="50" viewBox="0 -960 960 960" width="50">
          <path d="M504-480 320-664l56-56 240 240-240 240-56-56 184-184Z" />
        </svg>
      </span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
</div>

templates/_partials/_gitfLetter.html.twig
<div class="col-12 col-md-6 col-lg-4 px-2">
  <div class="w-100 bg-white bg-opacity-75 d-flex p-2 justify-content-between align-items-center my-2 rounded-2 col-12 col-md-6 col-lg-4" style="height: 75px;">
    <div class="text d-flex align-items-center h-100 w-auto">
      {% if gift.images is not empty %}
        <img style="width: 15%; aspect-ratio: 1;" class="object-fit-cover rounded-circle h-auto" src="{{ asset('/uploads/gifts/' ~ (gift.images|first)) }}" alt="photo de {{ gift.name }}" aria-label="image du cadeau {{ gift.name }}" />
      {% else %}
        <img style="width: 15%; aspect-ratio: 1;" class="object-fit-cover rounded-circle h-auto" src="{{ asset('/assets/images/x-masGift.jpeg') }}" alt="image par défaut de cadeau" aria-label="image par défaut de cadeau" />
      {% endif %}
      <span class="mx-2">{{ gift.name }}</span>
    </div>

    <button type="button" id="{{ gift.id }}" class="remove-gift btn btn-danger rounded-circle" role="button" aria-label="Supprimer le cadeau de la lettre">
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
        <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0z" />
        <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4zM2.5 3h11V2h-11z" />
      </svg>
    </button>
  </div>
</div>

templates/_partials/_navbar.html.twig
<nav class="col-12 col-md-auto fw-bold collapse navbar-collapse" id="navbarNav" aria-label="navigation menu">
  <ul class="navbar-nav d-flex-md justify-content-start ps-0">
    <li class="nav-item">
      <a role="link" aria-roledescription="link" href="{{ path('app_home') }}" class="nav-link mx-1 py-2 px-4 text-capitalize text-end text-lg-start
        {% if app.request.attributes.get('_route') is same as('app_home') %} text-secondary {% else %} text-primary {% endif %}">Accueil
      </a>
    </li>
    <li class="nav-item">
      <a role="link" aria-roledescription="link" href="{{ path('app_gift') }}" class="nav-link mx-1 py-2 px-4 text-capitalize text-end text-lg-start
        {% if app.request.attributes.get('_route') is same as('app_gift') or app.request.attributes.get('_route') is same as('app_gift_detail') %} text-secondary {% else %} text-primary {% endif %}">Salle aux Cadeaux
      </a>
    </li>
    <li class="nav-item">
      <a role="link" aria-roledescription="link" href="{{ path('app_letter') }}" class="nav-link mx-1 py-2 px-4 text-capitalize text-end text-lg-start
        {% if app.request.attributes.get('_route') is same as('app_letter') %} text-secondary {% else %} text-primary {% endif %}">Lettre au Père Noël
      </a>
    </li>
    <li class="nav-item">
      <a role="link" aria-roledescription="link" href="{{ path('app_contact') }}" class="nav-link mx-1 py-2 px-4 text-capitalize text-end text-lg-start
        {% if app.request.attributes.get('_route') is same as('app_contact') %} text-secondary {% else %} text-primary {% endif %}">Contact
      </a>
    </li>
  </ul>
</nav>

templates/_partials/_reindeers.html.twig
<div id="carouselReindeers" class="carousel slide" style="height: 300px;">
  <div class="carousel-inner h-100">
    {% for reindeer in reindeers %}
      <div class="h-100 col-12 col-md-6 col-lg-4 z-1 p-2 carousel-item {% if reindeer.name == 'Rudolph' %}active{% endif %} px-5">
        <div class="d-flex flex-row-reverse justify-content-center w-100 h-100 align-items-center px-5">
          {% if reindeer.fileName %}
            <img src="{{ asset('uploads/reindeers/' ~ reindeer.getFileName) }}" alt="image du renne de {{ reindeer.name }}" class="z-n1 w-auto h-100 object-fit-contain object-position-end" />
          {% else %}
            <img src="{{ asset('assets/images/reindeer.jpg') }}" alt="photot de {{ reindeer.name }}" class="z-n1 w-auto h-100 object-fit-contain" />
          {% endif %}
          <div class="text-start text-white carousel-caption d-none d-md-block w-75 h-100 position-static pe-2">
            <h3 class="fs-1 fw-bold glow">{{ reindeer.name }}</h3>
            <p>{{ reindeer.story }}</p>
          </div>
        </div>
      </div>
    {% endfor %}

    <button class="carousel-control-prev" type="button" data-bs-target="#carouselReindeers" data-bs-slide="prev">
      <span class="w-auto" aria-hidden="true">
        <svg xmlns="http://www.w3.org/2000/svg" height="50" viewBox="0 -960 960 960" width="50">
          <path d="M560-240 320-480l240-240 56 56-184 184 184 184-56 56Z" />
        </svg>
      </span>
      <span class="visually-hidden">Previous</span>
    </button>

    <button class="carousel-control-next" type="button" data-bs-target="#carouselReindeers" data-bs-slide="next">
      <span class="w-auto" aria-hidden="true">
        <svg xmlns="http://www.w3.org/2000/svg" height="50" viewBox="0 -960 960 960" width="50">
          <path d="M504-480 320-664l56-56 240 240-240 240-56-56 184-184Z" />
        </svg>
      </span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
</div>